// 广告数据字段中文标签映射（对齐源项目 MktAdReportConstants 字段）
export const AD_DATA_FIELD_LABELS = {
  // 通用属性
  created_at: '创建时间', updated_at: '更新时间', channel_id: '渠道ID', channel_name: '渠道',
  account_id: '账户ID', uid: '媒体账户ID', sys_user_id: '负责人ID', sys_user_name: '负责人',
  sys_sub_dep_id: '子部门ID', pid: '推广ID', app_id: '游戏', ad_id: '广告ID',
  subject_id: '主体ID', subject_name: '主体', aid: '创意ID', cid: '创意ID', cpid: '广告组ID',
  name: '名称', account_name: '账户名称', note: '备注', budget: '预算', mkt_balance: '余额',
  status: '状态', opt_status: '操作状态', is_deleted: '是否删除', scene_id: '投放场景',
  ad_type: '广告类型', daily_budget: '日预算',
  // 广告组/广告/创意
  campaign_name: '广告组名称', campaign_status: '广告组状态', campaign_budget: '广告组预算',
  campaign_type: '广告组类型', campaign_sub_type: '广告组子类型', campaign_ad_type: '广告组广告类型',
  campaign_bid_type: '广告组出价方式', unit_name: '广告名称', unit_status: '广告状态',
  unit_budget: '广告预算', promotion_content_type: '推广内容类型', speed_mode: '投放速度',
  base_target: '出价方式', base_bid: '目标出价', cpa_target: '转化目标', cpa_bid: '转化出价',
  deep_cpa_target: '深度转化目标', deep_cpa_bid: '深度出价', is_no_bid: '智能出价',
  creative_status: '创意状态', creative_name: '创意名称', demand_classify_id: '需求分类',
  demand_routine_id: '需求套路', budget_limit_type: '预算类型', support_auto: '自动投放',
  promotion_purpose_type: '推广目的',
  // 头条V3 项目/广告
  project_name: '项目名称', project_status: '项目状态', project_opt_status: '项目操作状态',
  project_budget: '项目预算', account_budget: '账户预算', promotion_name: '广告名称',
  landing_type: '落地页类型', pricing: '计费方式', inventory_catalog: '广告位大类',
  inventory_type: '广告位置', platform: '平台', marketing_goal: '营销目标',
  delivery_mode: '投放方式', deep_bid_type: '深度出价方式', bid_type: '出价方式',
  bid_speed: '出价速度', budget_mode: '预算类型', roi_goal: 'ROI目标',
  learning_phase: '学习阶段', is_copy_ad: '是否复制广告', compensation: '赔付',
  trusteeship_media_report_id: '托管报表ID', mkt_estimate_ecpm: '预估ECPM',
  // 腾讯
  site_set_name: '站点名称', adgroup_name: '广告组名称', marketing_sub_goal: '营销子目标',
  marketing_sub_goal_name: '营销子目标', auto_acquisition_enabled: '自动获取',
  auto_acquisition_enabled_name: '自动获取', bid_mode: '出价方式', bid_mode_name: '出价方式',
  bid_scene: '出价场景', bid_scene_name: '出价场景', deep_roi_goal: '深度ROI目标',
  deep_roi_goal_name: '深度ROI目标', system_status: '系统状态', system_status_name: '系统状态',
  configured_status: '配置状态', configured_status_name: '配置状态',
  optimization_goal: '优化目标', optimization_goal_name: '优化目标',
  auto_acquisition_status: '自动获取状态', auto_acquisition_status_name: '自动获取状态',
  dynamic_creative_name: '动态创意名称', adgroup_configured_status: '广告组配置状态',
  adgroup_configured_status_name: '广告组配置状态',
  auto_derived_program_creative_switch: '自动派生创意', auto_derived_program_creative_switch_name: '自动派生创意',
  // 媒体报表指标
  mkt_total_cost: '媒体消耗', mkt_acquisition_cost: '获取成本',
  mkt_total_fodder_impression: '媒体展示', mkt_total_fodder_click: '媒体点击',
  mkt_total_fodder_app_addiction: '媒体关键行为', mkt_total_register: '媒体注册',
  mkt_thousand_impression_cost: '千次展示成本', mkt_thousand_display_price: '千次展示均价',
  mkt_cpc: '点击成本', mkt_ctr: '点击率', mkt_total_dy_like_num: '抖音点赞',
  mkt_total_dy_comment_num: '抖音评论', mkt_total_dy_share_num: '抖音分享',
  mkt_total_dislike_num: '不喜欢', mkt_total_report_num: '举报',
  mkt_total_game_pay_count: '游戏付费数', mkt_total_active_pay: '活跃付费',
  mkt_attribution_active_pay_7d_per_count: '归因活跃付费7日', mkt_total_game_addiction: '游戏关键行为',
  mkt_game_addiction_cost: '关键行为成本', mkt_game_addiction_rate: '关键行为率',
  mkt_convert_cnt: '转化数', mkt_convert_cnt_cost: '转化成本', mkt_convert_cnt_rate: '转化率',
  mkt_pay_count_cost: '付费成本', pay_count_cost: '付费成本', mkt_pre_convert_count: '预转化数',
  mkt_pre_convert_cost: '预转化成本', mkt_pre_convert_rate: '预转化率',
  mkt_ratio_cost_click: '点击成本',
  // 小游戏指标
  mkt_mini_game_first_day_ad_monetization_amount: '首日广告变现',
  mkt_mini_game_income_roi_1: '首日收入ROI', mkt_minigame_3d_income_roi: '3日收入ROI',
  mkt_minigame_7d_income_roi: '7日收入ROI', mkt_minigame_14d_income_roi: '14日收入ROI',
  mkt_minigame_30d_income_roi: '30日收入ROI', mkt_minigame_24h_income_roi: '24小时收入ROI',
  mkt_mini_game_ad_monetization_amount_d3: '3日广告变现',
  mkt_mini_game_ad_monetization_amount_d7: '7日广告变现',
  mkt_mini_game_ad_monetization_amount_d14: '14日广告变现',
  mkt_mini_game_ad_monetization_amount_d30: '30日广告变现',
  mkt_minigame_24h_mix_income_roi: '24小时混合变现ROI',
  mkt_minigame_1d_mix_income_roi: '1日混合变现ROI',
  mkt_minigame_7d_mix_income_roi: '7日混合变现ROI',
  mkt_minigame_14d_mix_income_roi: '14日混合变现ROI',
  mkt_minigame_30d_mix_income_roi: '30日混合变现ROI',
  mkt_mini_game_register_users_cnt: '小游戏注册用户', mkt_mini_game_register_cost: '小游戏注册成本',
  mkt_mini_game_register_users_cnt_rate: '小游戏注册率',
  mkt_mini_game_paying_users_d1: '首日付费用户', mkt_mini_game_paying_amount_d1: '首日付费金额',
  mkt_mini_game_first_day_paying_roi: '首日付费ROI', mkt_mini_game_paying_amount_d7: '7日付费金额',
  mkt_mini_game_pay_d7_roi: '7日付费ROI', mkt_mini_game_paying_amount_d30: '30日付费金额',
  mkt_mini_game_pay_d30_roi: '30日付费ROI', mkt_mini_game_bf_uv: '小游戏暴风UV',
  mkt_mini_game_bf_cost: '小游戏暴风成本', mkt_mini_game_bf_purchase_uv: '暴风购买UV',
  mkt_mini_game_bf_purchase_amount: '暴风购买金额', mkt_mini_game_bf_purchase_roi: '暴风购买ROI',
  mkt_mini_game_first_day_ad_monetization_users: '首日广告变现用户',
  mkt_income_pv_24h_pla: '24小时变现PV', mkt_mini_game_first_day_ad_paying_cost: '首日广告付费成本',
  mkt_mini_game_first_day_ad_paying_arpu: '首日广告付费ARPU', mkt_minigame_3d_income_uv: '3日变现UV',
  mkt_minigame_3d_income_count: '3日变现次数', mkt_income_roi_1_24h_pla: '24小时收入ROI',
  mkt_mini_game_pay_in_24h_amount_roi: '24小时付费金额ROI',
  mkt_mini_game_pay_in_24h_arrive_coefficient: '24小时付费达标系数',
  mkt_purchase_pla_clk_1d_amount_roi: '点击1日购买金额ROI',
  mkt_purchase_pla_clk_1d_arrive_coefficient: '点击1日购买达标系数',
  // 投放报表指标
  total_cost: '消耗', total_active: '激活', total_reg: '注册', ratio_reg_cost: '注册成本',
  total_new_num: '新增', rate_new_num: '新增率', ratio_fee_cost: '付费成本',
  ratio_new_arppu: '新增ARPPU', total_fee_num: '付费数', total_fee_count: '付费次数',
  total_purchase: '购买', total_roi_profit: '付费ROI', rate_roi_profit: 'ROI',
  rate_roi_profit_1: '首日ROI', rate_roi_1: '首日ROI', ratio_role_cost: '角色成本',
  total_fee_100: '100元付费', ratio_fee_100_cost: '100元付费成本',
  ratio_reg_coin_cost: '注册金币成本', total_new_sum: '新增金额', rate_role_reg: '角色注册率',
  rate_new_remain_eq_2: '2日留存', ratio_roi_profit_x_2: '双倍ROI',
  mkt_exchange_cash_ecpm: '兑换现金ECPM', total_behavior_reg_ecpm_count: '行为注册ECPM',
  ratio_behavior_ecpm: '行为ECPM', rate_reg_behavior_ecpm_roi: '注册行为ECPM ROI',
  rate_day_behavior_ecpm_roi: '日行为ECPM ROI',
  mkt_total_click_start_cnt: '点击开始数', mkt_ratio_cost_click_start: '点击开始成本',
  mkt_rate_click_start: '点击开始率', mkt_total_download_finish_cnt: '下载完成数',
  mkt_ratio_cost_download_finish: '下载完成成本', mkt_rate_download_finish: '下载完成率',
  mkt_total_install_finish_cnt: '安装完成数', rate_fodder_click: '素材点击率',
  rate_fee_fodder_click: '付费素材点击率', mkt_last_absolute_cost: '最近绝对消耗',
  mkt_last_diff_cost: '最近差异消耗', mkt_last_absolute_impression: '最近绝对展示',
  mkt_last_diff_impression: '最近差异展示', mkt_force_close_rate: '强退率',
}

// 构建广告数据表格列
export function buildColumns(fields) {
  return fields.map((f) => ({
    title: AD_DATA_FIELD_LABELS[f] || f,
    key: f,
    ellipsis: { tooltip: true },
  }))
}

export const AD_DATA_LEVEL_TABS = [
  { key: 'account', label: '账户' },
  { key: 'campaign', label: '第一层级' },
  { key: 'unit', label: '第二层级' },
  { key: 'creative', label: '第三层级' },
]